### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.aethos/config.yml'

### ISSUE THREAD

**Issue by lucasnewkirk** [Ashton-Sidhu/aethos#106]
**Describe the bug**
After I did 'pip install aethos', I tried to create a data science folder structure with 'aethos create'. I also just tried to import using 'import aethos as at' and both yielded the same error:

**FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/.aethos/config.yml'**

It seems that aethos is looking in the wrong place for the config file. Everything is stored in my Anaconda distro:

![image](https://user-images.githubusercontent.com/19437239/72214580-c1578d00-34ca-11ea-81d3-254440bd6ce2.png)

**To Reproduce**
Try either 'aethos create' or importing in Jupyter Notebook (I have Jupyter 6.0.1, if that matters).

**Expected behavior**
I didn't expect to receive an error. I wanted to work with this promising package. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19437239/72214540-cb2cc080-34c9-11ea-82ed-d1f3ed02780b.png)

**Desktop (please complete the following information):**
 - OS: Linux pop-os 5.3.0-7625-generic
 - Browser: Mozilla Firefox 72.0.1

**Comment by Ashton-Sidhu** [comment]
Hey thanks for your feedback! I just pushed a commit that should fix this issue and will push a release today.

**Comment by Ashton-Sidhu** [comment]
The issue should be resolved now! Run `pip install -U aethos`

**Comment by lucasnewkirk** [comment]
Perfect. I'm loving 'aethos create'. Thanks for putting in the hard work here. I'll be keeping up with aethos and spreading the word to other data scientists.
