### ISSUE TITLE
OSError when installing or creating folder structure  

### ISSUE THREAD

**Issue by aworleo** [Ashton-Sidhu/aethos#108]
**Describe the bug**
After I did 'pip install aethos', I attempted the following 

1. creating  DS folder structure with 'aethos create' 
2.  installing  NLP corpora with  'aethos install-corpora,
3. Enabling extensions with 'aethos enable-extensions'

All yielded the same error message 

**OSError: dlopen(/usr/local/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
Reason: image not found**

**To Reproduce**
try installing, creating or enabling aextensions 
**Expected behavior**
I wasn't expecting any error.I wanted to follow your example that you posted on Medium

![Screen Shot 2020-01-25 at 1 38 49 AM](https://user-images.githubusercontent.com/38052686/73118118-4acc7d80-3f15-11ea-95fa-da9801649d5b.png)

OS: MacOS
Browser: Safari/Chrome

**Comment by aworleo** [comment]
![Screen Shot 2020-01-25 at 1 33 54 AM](https://user-images.githubusercontent.com/38052686/73118081-8e72b780-3f14-11ea-8883-1dc52f032aa2.png)

**Comment by Ashton-Sidhu** [comment]
Hey! Thanks for trying Aethos. This seems to be an issue regarding MacOS and LightGBM compatibility. 

1) If you try pip installing Aethos in a virtual environment does the error persist?

2) There are some solutions in this thread that you can also try: https://github.com/microsoft/LightGBM/issues/1369 . Let me know how it goes!

**Comment by aworleo** [comment]
Hi Ashton, I used tried number 2 and it worked :) Thanks

**Comment by aworleo** [comment]
I tried solutions listed in (2) and it worked.. :) Thanks
