### ISSUE TITLE
aethos install-corpora failing to find python3 command on windows

### ISSUE THREAD

**Issue by ganesh3** [Ashton-Sidhu/aethos#109]
**Describe the bug**
I ran the command >aethos install-corpora to setup but got the below error.
'python3' is not recognized as an internal or external command,
operable program or batch file.
'python3' is not recognized as an internal or external command,
operable program or batch file.
'python3' is not recognized as an internal or external command,
operable program or batch file.

**To Reproduce**
1) Setup a new virtual environment on Windows 2
2) pip install aethos
3) pip install aethos[ptmodels]
4) aethos install-corpora (errors out as above)

Windows does not have python3 as a command and has python which can be used to execute python program.

**Expected behavior**
Installatoon of corpora packages.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Anaconda prompt cmd line execution
 - python 3.8

**Comment by Ashton-Sidhu** [comment]
Hey, just pushed a fix for this. You can run `pip install -U aethos` and give it a try.

**Comment by ganesh3** [comment]
Its working now. Thanks.
